---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clustersecret-operator.controller.fullname" . }}
  labels:
    {{- include "clustersecret-operator.controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "clustersecret-operator.controller.fullname" . }}
  labels:
    {{- include "clustersecret-operator.controller.labels" . | nindent 4 }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  resourceNames: ["{{ include "clustersecret-operator.controller.fullname" . }}"]
  verbs: ["get","list","watch","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "clustersecret-operator.controller.fullname" . }}
  labels:
    {{- include "clustersecret-operator.controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "clustersecret-operator.controller.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "clustersecret-operator.controller.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clustersecret-operator.controller.fullname" . }}
  labels:
    {{- include "clustersecret-operator.controller.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list","watch"]
- apiGroups: ["core.cs.sap.com"]
  resources: ["clustersecrets","clustersecrets/status"]
  verbs:  ["get","list","watch","update"]
- apiGroups: ["","events.k8s.io"]
  resources: ["events"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clustersecret-operator.controller.fullname" . }}
  labels:
    {{- include "clustersecret-operator.controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "clustersecret-operator.controller.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clustersecret-operator.controller.fullname" . }}
